
// this is an automatically generated file. see `GenStrObjInitializer.py` for it's generation code.
#define NUM_STD_SYMBOLS 51
struct {
	const char* symbol;
	void* address;
	uint32_t label;
	uint8_t expectedType;
} stdObjects[NUM_STD_SYMBOLS]={
	[0].address=&_assert,[0].symbol="_assert",[0].expectedType=5,
	[1].address=&_static_var_strtok,[1].symbol="_static_var_strtok",[1].expectedType=1,
	[2].address=&abort,[2].symbol="abort",[2].expectedType=5,
	[3].address=&calloc,[3].symbol="calloc",[3].expectedType=5,
	[4].address=&clearerr,[4].symbol="clearerr",[4].expectedType=5,
	[5].address=&exit,[5].symbol="exit",[5].expectedType=5,
	[6].address=&fclose,[6].symbol="fclose",[6].expectedType=5,
	[7].address=&feof,[7].symbol="feof",[7].expectedType=5,
	[8].address=&ferror,[8].symbol="ferror",[8].expectedType=5,
	[9].address=&fflush,[9].symbol="fflush",[9].expectedType=5,
	[10].address=&fgetc,[10].symbol="fgetc",[10].expectedType=5,
	[11].address=&fgetpos,[11].symbol="fgetpos",[11].expectedType=5,
	[12].address=&fgets,[12].symbol="fgets",[12].expectedType=5,
	[13].address=&fopen,[13].symbol="fopen",[13].expectedType=5,
	[14].address=&fprintf,[14].symbol="fprintf",[14].expectedType=5,
	[15].address=&fputc,[15].symbol="fputc",[15].expectedType=5,
	[16].address=&fread,[16].symbol="fread",[16].expectedType=5,
	[17].address=&free,[17].symbol="free",[17].expectedType=5,
	[18].address=&fseek,[18].symbol="fseek",[18].expectedType=5,
	[19].address=&fsetpos,[19].symbol="fsetpos",[19].expectedType=5,
	[20].address=&ftell,[20].symbol="ftell",[20].expectedType=5,
	[21].address=&fwrite,[21].symbol="fwrite",[21].expectedType=5,
	[22].address=&malloc,[22].symbol="malloc",[22].expectedType=5,
	[23].address=&memchr,[23].symbol="memchr",[23].expectedType=5,
	[24].address=&memcmp,[24].symbol="memcmp",[24].expectedType=5,
	[25].address=&memcpy,[25].symbol="memcpy",[25].expectedType=5,
	[26].address=&memmove,[26].symbol="memmove",[26].expectedType=5,
	[27].address=&memset,[27].symbol="memset",[27].expectedType=5,
	[28].address=&printf,[28].symbol="printf",[28].expectedType=5,
	[29].address=&realloc,[29].symbol="realloc",[29].expectedType=5,
	[30].address=&rewind,[30].symbol="rewind",[30].expectedType=5,
	[31].address=&snprintf,[31].symbol="snprintf",[31].expectedType=5,
	[32].address=&stderr,[32].symbol="stderr",[32].expectedType=1,
	[33].address=&stdin,[33].symbol="stdin",[33].expectedType=1,
	[34].address=&stdout,[34].symbol="stdout",[34].expectedType=1,
	[35].address=&strcat,[35].symbol="strcat",[35].expectedType=5,
	[36].address=&strchr,[36].symbol="strchr",[36].expectedType=5,
	[37].address=&strcmp,[37].symbol="strcmp",[37].expectedType=5,
	[38].address=&strcpy,[38].symbol="strcpy",[38].expectedType=5,
	[39].address=&strcspn,[39].symbol="strcspn",[39].expectedType=5,
	[40].address=&strlen,[40].symbol="strlen",[40].expectedType=5,
	[41].address=&strncat,[41].symbol="strncat",[41].expectedType=5,
	[42].address=&strncmp,[42].symbol="strncmp",[42].expectedType=5,
	[43].address=&strncpy,[43].symbol="strncpy",[43].expectedType=5,
	[44].address=&strpbrk,[44].symbol="strpbrk",[44].expectedType=5,
	[45].address=&strrchr,[45].symbol="strrchr",[45].expectedType=5,
	[46].address=&strspn,[46].symbol="strspn",[46].expectedType=5,
	[47].address=&strstr,[47].symbol="strstr",[47].expectedType=5,
	[48].address=&strtok,[48].symbol="strtok",[48].expectedType=5,
	[49].address=&ungetc,[49].symbol="ungetc",[49].expectedType=5,
	[50].address=&vsprintf,[50].symbol="vsprintf",[50].expectedType=5
};
