void printSingleInstructionOptCode(const InstructionSingle instructionSingle){
switch(instructionSingle.id){
case I_NOP_:printf("NOP_");break;
case I_PU1_:printf("PU1_ %%%01X",instructionSingle.arg.B1.a_0);break;
case I_PU2_:printf("PU2_ %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_PUA1:printf("PUA1 %%%01X",instructionSingle.arg.B1.a_0);break;
case I_PUA2:printf("PUA2 %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_POP1:printf("POP1 %%%01X",instructionSingle.arg.B1.a_0);break;
case I_POP2:printf("POP2 %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_BL1_:printf("BL1_ %%%01X $%02X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_RL1_:printf("RL1_ %%%01X #%04X",instructionSingle.arg.BW.a_0,instructionSingle.arg.BW.a_1);break;
case I_RL2_:printf("RL2_ %%%01X %%%01X !%08X",instructionSingle.arg.BBD.a_0,instructionSingle.arg.BBD.a_1,instructionSingle.arg.BBD.a_2);break;
case I_CALL:printf("CALL %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_RET_:printf("RET_");break;
case I_STPA:printf("STPA %%%01X #%04X",instructionSingle.arg.BW.a_0,instructionSingle.arg.BW.a_1);break;
case I_STPS:printf("STPS %%%01X #%04X",instructionSingle.arg.BW.a_0,instructionSingle.arg.BW.a_1);break;
case I_STWN:printf("STWN %%%01X $%02X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_STRN:printf("STRN %%%01X $%02X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_STWV:printf("STWV %%%01X $%02X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_STRV:printf("STRV %%%01X $%02X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_ALOC:printf("ALOC");break;
case I_ALCR:printf("ALCR %%%01X #%04X",instructionSingle.arg.BW.a_0,instructionSingle.arg.BW.a_1);break;
case I_STOF:printf("STOF %%%01X #%04X",instructionSingle.arg.BW.a_0,instructionSingle.arg.BW.a_1);break;
case I_AJMP:printf("AJMP %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_CJMP:printf("CJMP %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_JJMP:printf("JJMP %%%01X %%%01X :%08X",instructionSingle.arg.BBD.a_0,instructionSingle.arg.BBD.a_1,instructionSingle.arg.BBD.a_2);break;
case I_JTEN:printf("JTEN @%08X",instructionSingle.arg.D.a_0);break;
case I_JEND:printf("JEND");break;
case I_MOV_:printf("MOV_ %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_AND_:printf("AND_ %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_OR__:printf("OR__ %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_XOR_:printf("XOR_ %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_SSUB:printf("SSUB %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_ADDN:printf("ADDN %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_SUBN:printf("SUBN %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_SUBC:printf("SUBC %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_MULS:printf("MULS %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_MULL:printf("MULL %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_DIVM:printf("DIVM %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_SHFT:printf("SHFT %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_BSWP:printf("BSWP %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_MWWN:printf("MWWN %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_MRWN:printf("MRWN %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_MWWV:printf("MWWV %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_MRWV:printf("MRWV %%%01X %%%01X %%%01X",instructionSingle.arg.B3.a_0,instructionSingle.arg.B3.a_1,instructionSingle.arg.B3.a_2);break;
case I_MWBN:printf("MWBN %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_MRBN:printf("MRBN %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_MWBV:printf("MWBV %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_MRBV:printf("MRBV %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_LABL:printf("LABL :%08X",instructionSingle.arg.D.a_0);break;
case I_PHIS:printf("PHIS %%%01X",instructionSingle.arg.B1.a_0);break;
case I_PHIE:printf("PHIE %%%01X",instructionSingle.arg.B1.a_0);break;
case I_FCST:printf("FCST $%02X #%04X :%08X",instructionSingle.arg.BWD.a_0,instructionSingle.arg.BWD.a_1,instructionSingle.arg.BWD.a_2);break;
case I_FCEN:printf("FCEN");break;
case I_D32U:printf("D32U");break;
case I_R32U:printf("R32U");break;
case I_D32S:printf("D32S");break;
case I_R32S:printf("R32S");break;
case I_D64U:printf("D64U");break;
case I_R64U:printf("R64U");break;
case I_D64S:printf("D64S");break;
case I_R64S:printf("R64S");break;
case I_LAD0:printf("LAD0 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B6.a_0,instructionSingle.arg.B6.a_1,instructionSingle.arg.B6.a_2,instructionSingle.arg.B6.a_3,instructionSingle.arg.B6.a_4,instructionSingle.arg.B6.a_5);break;
case I_LAD1:printf("LAD1 %%%01X %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B5.a_0,instructionSingle.arg.B5.a_1,instructionSingle.arg.B5.a_2,instructionSingle.arg.B5.a_3,instructionSingle.arg.B5.a_4);break;
case I_LAD2:printf("LAD2 %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B4.a_0,instructionSingle.arg.B4.a_1,instructionSingle.arg.B4.a_2,instructionSingle.arg.B4.a_3);break;
case I_LAD3:printf("LAD3 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B8.a_0,instructionSingle.arg.B8.a_1,instructionSingle.arg.B8.a_2,instructionSingle.arg.B8.a_3,instructionSingle.arg.B8.a_4,instructionSingle.arg.B8.a_5,instructionSingle.arg.B8.a_6,instructionSingle.arg.B8.a_7);break;
case I_LAD4:printf("LAD4");break;
case I_LAD5:printf("LAD5");break;
case I_LSU0:printf("LSU0 %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B4.a_0,instructionSingle.arg.B4.a_1,instructionSingle.arg.B4.a_2,instructionSingle.arg.B4.a_3);break;
case I_LSU3:printf("LSU3 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B8.a_0,instructionSingle.arg.B8.a_1,instructionSingle.arg.B8.a_2,instructionSingle.arg.B8.a_3,instructionSingle.arg.B8.a_4,instructionSingle.arg.B8.a_5,instructionSingle.arg.B8.a_6,instructionSingle.arg.B8.a_7);break;
case I_LSU4:printf("LSU4");break;
case I_LSU5:printf("LSU5");break;
case I_LMU3:printf("LMU3 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B8.a_0,instructionSingle.arg.B8.a_1,instructionSingle.arg.B8.a_2,instructionSingle.arg.B8.a_3,instructionSingle.arg.B8.a_4,instructionSingle.arg.B8.a_5,instructionSingle.arg.B8.a_6,instructionSingle.arg.B8.a_7);break;
case I_LMU4:printf("LMU4");break;
case I_LMU5:printf("LMU5");break;
case I_LDI4:printf("LDI4");break;
case I_LDI5:printf("LDI5");break;
case I_LLS6:printf("LLS6");break;
case I_LLS7:printf("LLS7");break;
case I_LRS6:printf("LRS6");break;
case I_LRS7:printf("LRS7");break;
case I_SYRB:printf("SYRB %%%01X",instructionSingle.arg.B1.a_0);break;
case I_SYRW:printf("SYRW %%%01X",instructionSingle.arg.B1.a_0);break;
case I_SYRD:printf("SYRD %%%01X %%%01X",instructionSingle.arg.B2.a_0,instructionSingle.arg.B2.a_1);break;
case I_SYRQ:printf("SYRQ %%%01X %%%01X %%%01X %%%01X",instructionSingle.arg.B4.a_0,instructionSingle.arg.B4.a_1,instructionSingle.arg.B4.a_2,instructionSingle.arg.B4.a_3);break;
case I_SYRE:printf("SYRE");break;
case I_NSNB:printf("NSNB !%08X",instructionSingle.arg.D.a_0);break;
case I_ZNXB:printf("ZNXB !%08X",instructionSingle.arg.D.a_0);break;
case I_BYTE:printf("BYTE $%02X",instructionSingle.arg.B1.a_0);break;
case I_WORD:printf("WORD #%04X",instructionSingle.arg.W.a_0);break;
case I_DWRD:printf("DWRD !%08X",instructionSingle.arg.D.a_0);break;
case I_SYDB:printf("SYDB");break;
case I_SYDW:printf("SYDW");break;
case I_SYDD:printf("SYDD");break;
case I_SYDQ:printf("SYDQ");break;
case I_SYDE:printf("SYDE");break;
case I_SYCB:printf("SYCB $%02X",instructionSingle.arg.B1.a_0);break;
case I_SYCW:printf("SYCW #%04X",instructionSingle.arg.W.a_0);break;
case I_SYCD:printf("SYCD !%08X",instructionSingle.arg.D.a_0);break;
case I_SYCL:printf("SYCL @%08X",instructionSingle.arg.D.a_0);break;
case I_SYW0:printf("SYW0");break;
case I_SYW1:printf("SYW1");break;
case I_SYW2:printf("SYW2");break;
case I_SYW3:printf("SYW3");break;
case I_SYW4:printf("SYW4");break;
case I_SYW5:printf("SYW5");break;
case I_SYW6:printf("SYW6");break;
case I_SYW7:printf("SYW7");break;
case I_SYW8:printf("SYW8");break;
case I_SYW9:printf("SYW9");break;
case I_SBLW:printf("SBLW");break;
case I_SBRW:printf("SBRW");break;
case I_SYD0:printf("SYD0");break;
case I_SYD1:printf("SYD1");break;
case I_SYD2:printf("SYD2");break;
case I_SYD3:printf("SYD3");break;
case I_SYD4:printf("SYD4");break;
case I_SYD5:printf("SYD5");break;
case I_SYD6:printf("SYD6");break;
case I_SYD7:printf("SYD7");break;
case I_SYD8:printf("SYD8");break;
case I_SYD9:printf("SYD9");break;
case I_SBLD:printf("SBLD");break;
case I_SBRD:printf("SBRD");break;
case I_SYQ0:printf("SYQ0");break;
case I_SYQ1:printf("SYQ1");break;
case I_SYQ2:printf("SYQ2");break;
case I_SYQ3:printf("SYQ3");break;
case I_SYQ4:printf("SYQ4");break;
case I_SYQ5:printf("SYQ5");break;
case I_SYQ6:printf("SYQ6");break;
case I_SYQ7:printf("SYQ7");break;
case I_SYQ8:printf("SYQ8");break;
case I_SYQ9:printf("SYQ9");break;
case I_SBLQ:printf("SBLQ");break;
case I_SBRQ:printf("SBRQ");break;
case I_SCBW:printf("SCBW");break;
case I_SCWD:printf("SCWD");break;
case I_SCDQ:printf("SCDQ");break;
case I_SCQD:printf("SCQD");break;
case I_SCDW:printf("SCDW");break;
case I_SCWB:printf("SCWB");break;
case I_SCDB:printf("SCDB");break;
case I_SCQB:printf("SCQB");break;
case I_SCZD:printf("SCZD");break;
case I_SCZQ:printf("SCZQ");break;
case I_ERR_:printf("ERR_");break;
case I_DEPL:printf("DEPL");break;
case I_PEPH:printf("PEPH");break;
case I_STPI:printf("STPI %%%01X #%04X",instructionSingle.arg.BW.a_0,instructionSingle.arg.BW.a_1);break;
case I_LOFF:printf("LOFF !%08X",instructionSingle.arg.D.a_0);break;
case I_INSR:printf("INSR %%%01X",instructionSingle.arg.B1.a_0);break;
}
}
