void printSingleInstructionOptCode(const InstructionSingle instructionSingle){
switch(instructionSingle.id){
case I_NOP_:printf("NOP_");return;
case I_PU1_:printf("PU1_ %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_PU2_:printf("PU2_ %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_PUA1:printf("PUA1 %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_PUA2:printf("PUA2 %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_POP1:printf("POP1 %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_POP2:printf("POP2 %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_BL1_:printf("BL1_ %%%01X $%02X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_RL1_:printf("RL1_ %%%01X #%04X",(uint16_t)instructionSingle.arg.BW.a_0,(uint16_t)instructionSingle.arg.BW.a_1);return;
case I_RL2_:printf("RL2_ %%%01X %%%01X !%04X%04X",(uint16_t)instructionSingle.arg.BBD.a_0,(uint16_t)instructionSingle.arg.BBD.a_1,(uint16_t)(instructionSingle.arg.BBD.a_2>>16),(uint16_t)instructionSingle.arg.BBD.a_2);return;
case I_CALL:printf("CALL %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_RET_:printf("RET_");return;
case I_STPA:printf("STPA %%%01X #%04X",(uint16_t)instructionSingle.arg.BW.a_0,(uint16_t)instructionSingle.arg.BW.a_1);return;
case I_STPS:printf("STPS %%%01X #%04X",(uint16_t)instructionSingle.arg.BW.a_0,(uint16_t)instructionSingle.arg.BW.a_1);return;
case I_STWN:printf("STWN %%%01X $%02X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_STRN:printf("STRN %%%01X $%02X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_STWV:printf("STWV %%%01X $%02X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_STRV:printf("STRV %%%01X $%02X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_ALOC:printf("ALOC");return;
case I_ALCR:printf("ALCR %%%01X #%04X",(uint16_t)instructionSingle.arg.BW.a_0,(uint16_t)instructionSingle.arg.BW.a_1);return;
case I_STOF:printf("STOF %%%01X #%04X",(uint16_t)instructionSingle.arg.BW.a_0,(uint16_t)instructionSingle.arg.BW.a_1);return;
case I_AJMP:printf("AJMP %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_CJMP:printf("CJMP %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_JJMP:printf("JJMP %%%01X %%%01X :%04X%04X",(uint16_t)instructionSingle.arg.BBD.a_0,(uint16_t)instructionSingle.arg.BBD.a_1,(uint16_t)(instructionSingle.arg.BBD.a_2>>16),(uint16_t)instructionSingle.arg.BBD.a_2);return;
case I_JTEN:printf("JTEN @%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_JEND:printf("JEND");return;
case I_MOV_:printf("MOV_ %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_AND_:printf("AND_ %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_OR__:printf("OR__ %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_XOR_:printf("XOR_ %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_SSUB:printf("SSUB %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_ADDN:printf("ADDN %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_SUBN:printf("SUBN %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_SUBC:printf("SUBC %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_MULS:printf("MULS %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_MULL:printf("MULL %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_DIVM:printf("DIVM %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_SHFT:printf("SHFT %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_BSWP:printf("BSWP %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_MWWN:printf("MWWN %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_MRWN:printf("MRWN %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_MWWV:printf("MWWV %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_MRWV:printf("MRWV %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B3.a_0,(uint16_t)instructionSingle.arg.B3.a_1,(uint16_t)instructionSingle.arg.B3.a_2);return;
case I_MWBN:printf("MWBN %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_MRBN:printf("MRBN %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_MWBV:printf("MWBV %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_MRBV:printf("MRBV %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_LABL:printf("LABL :%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_PHIS:printf("PHIS %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_PHIE:printf("PHIE %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_FCST:printf("FCST $%02X #%04X :%04X%04X",(uint16_t)instructionSingle.arg.BWD.a_0,(uint16_t)instructionSingle.arg.BWD.a_1,(uint16_t)(instructionSingle.arg.BWD.a_2>>16),(uint16_t)instructionSingle.arg.BWD.a_2);return;
case I_FCEN:printf("FCEN");return;
case I_D32U:printf("D32U");return;
case I_R32U:printf("R32U");return;
case I_D32S:printf("D32S");return;
case I_R32S:printf("R32S");return;
case I_D64U:printf("D64U");return;
case I_R64U:printf("R64U");return;
case I_D64S:printf("D64S");return;
case I_R64S:printf("R64S");return;
case I_LAD0:printf("LAD0 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B6.a_0,(uint16_t)instructionSingle.arg.B6.a_1,(uint16_t)instructionSingle.arg.B6.a_2,(uint16_t)instructionSingle.arg.B6.a_3,(uint16_t)instructionSingle.arg.B6.a_4,(uint16_t)instructionSingle.arg.B6.a_5);return;
case I_LAD1:printf("LAD1 %%%01X %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B5.a_0,(uint16_t)instructionSingle.arg.B5.a_1,(uint16_t)instructionSingle.arg.B5.a_2,(uint16_t)instructionSingle.arg.B5.a_3,(uint16_t)instructionSingle.arg.B5.a_4);return;
case I_LAD2:printf("LAD2 %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B4.a_0,(uint16_t)instructionSingle.arg.B4.a_1,(uint16_t)instructionSingle.arg.B4.a_2,(uint16_t)instructionSingle.arg.B4.a_3);return;
case I_LAD3:printf("LAD3 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B8.a_0,(uint16_t)instructionSingle.arg.B8.a_1,(uint16_t)instructionSingle.arg.B8.a_2,(uint16_t)instructionSingle.arg.B8.a_3,(uint16_t)instructionSingle.arg.B8.a_4,(uint16_t)instructionSingle.arg.B8.a_5,(uint16_t)instructionSingle.arg.B8.a_6,(uint16_t)instructionSingle.arg.B8.a_7);return;
case I_LAD4:printf("LAD4");return;
case I_LAD5:printf("LAD5");return;
case I_LSU0:printf("LSU0 %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B4.a_0,(uint16_t)instructionSingle.arg.B4.a_1,(uint16_t)instructionSingle.arg.B4.a_2,(uint16_t)instructionSingle.arg.B4.a_3);return;
case I_LSU3:printf("LSU3 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B8.a_0,(uint16_t)instructionSingle.arg.B8.a_1,(uint16_t)instructionSingle.arg.B8.a_2,(uint16_t)instructionSingle.arg.B8.a_3,(uint16_t)instructionSingle.arg.B8.a_4,(uint16_t)instructionSingle.arg.B8.a_5,(uint16_t)instructionSingle.arg.B8.a_6,(uint16_t)instructionSingle.arg.B8.a_7);return;
case I_LSU4:printf("LSU4");return;
case I_LSU5:printf("LSU5");return;
case I_LMU3:printf("LMU3 %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B8.a_0,(uint16_t)instructionSingle.arg.B8.a_1,(uint16_t)instructionSingle.arg.B8.a_2,(uint16_t)instructionSingle.arg.B8.a_3,(uint16_t)instructionSingle.arg.B8.a_4,(uint16_t)instructionSingle.arg.B8.a_5,(uint16_t)instructionSingle.arg.B8.a_6,(uint16_t)instructionSingle.arg.B8.a_7);return;
case I_LMU4:printf("LMU4");return;
case I_LMU5:printf("LMU5");return;
case I_LDI4:printf("LDI4");return;
case I_LDI5:printf("LDI5");return;
case I_LLS6:printf("LLS6");return;
case I_LLS7:printf("LLS7");return;
case I_LRS6:printf("LRS6");return;
case I_LRS7:printf("LRS7");return;
case I_SYRB:printf("SYRB %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_SYRW:printf("SYRW %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_SYRD:printf("SYRD %%%01X %%%01X",(uint16_t)instructionSingle.arg.B2.a_0,(uint16_t)instructionSingle.arg.B2.a_1);return;
case I_SYRQ:printf("SYRQ %%%01X %%%01X %%%01X %%%01X",(uint16_t)instructionSingle.arg.B4.a_0,(uint16_t)instructionSingle.arg.B4.a_1,(uint16_t)instructionSingle.arg.B4.a_2,(uint16_t)instructionSingle.arg.B4.a_3);return;
case I_SYRE:printf("SYRE");return;
case I_NSNB:printf("NSNB !%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_ZNXB:printf("ZNXB !%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_BYTE:printf("BYTE $%02X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_WORD:printf("WORD #%04X",(uint16_t)instructionSingle.arg.W.a_0);return;
case I_DWRD:printf("DWRD !%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_SYDB:printf("SYDB");return;
case I_SYDW:printf("SYDW");return;
case I_SYDD:printf("SYDD");return;
case I_SYDQ:printf("SYDQ");return;
case I_SYDE:printf("SYDE");return;
case I_SYCB:printf("SYCB $%02X",(uint16_t)instructionSingle.arg.B1.a_0);return;
case I_SYCW:printf("SYCW #%04X",(uint16_t)instructionSingle.arg.W.a_0);return;
case I_SYCD:printf("SYCD !%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_SYCL:printf("SYCL @%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_SYW0:printf("SYW0");return;
case I_SYW1:printf("SYW1");return;
case I_SYW2:printf("SYW2");return;
case I_SYW3:printf("SYW3");return;
case I_SYW4:printf("SYW4");return;
case I_SYW5:printf("SYW5");return;
case I_SYW6:printf("SYW6");return;
case I_SYW7:printf("SYW7");return;
case I_SYW8:printf("SYW8");return;
case I_SYW9:printf("SYW9");return;
case I_SBLW:printf("SBLW");return;
case I_SBRW:printf("SBRW");return;
case I_SYD0:printf("SYD0");return;
case I_SYD1:printf("SYD1");return;
case I_SYD2:printf("SYD2");return;
case I_SYD3:printf("SYD3");return;
case I_SYD4:printf("SYD4");return;
case I_SYD5:printf("SYD5");return;
case I_SYD6:printf("SYD6");return;
case I_SYD7:printf("SYD7");return;
case I_SYD8:printf("SYD8");return;
case I_SYD9:printf("SYD9");return;
case I_SBLD:printf("SBLD");return;
case I_SBRD:printf("SBRD");return;
case I_SYQ0:printf("SYQ0");return;
case I_SYQ1:printf("SYQ1");return;
case I_SYQ2:printf("SYQ2");return;
case I_SYQ3:printf("SYQ3");return;
case I_SYQ4:printf("SYQ4");return;
case I_SYQ5:printf("SYQ5");return;
case I_SYQ6:printf("SYQ6");return;
case I_SYQ7:printf("SYQ7");return;
case I_SYQ8:printf("SYQ8");return;
case I_SYQ9:printf("SYQ9");return;
case I_SBLQ:printf("SBLQ");return;
case I_SBRQ:printf("SBRQ");return;
case I_SCBW:printf("SCBW");return;
case I_SCWD:printf("SCWD");return;
case I_SCDQ:printf("SCDQ");return;
case I_SCQD:printf("SCQD");return;
case I_SCDW:printf("SCDW");return;
case I_SCWB:printf("SCWB");return;
case I_SCDB:printf("SCDB");return;
case I_SCQB:printf("SCQB");return;
case I_SCZD:printf("SCZD");return;
case I_SCZQ:printf("SCZQ");return;
case I_ERR_:printf("ERR_");return;
case I_DEPL:printf("DEPL");return;
case I_PEPH:printf("PEPH");return;
case I_STPI:printf("STPI %%%01X #%04X",(uint16_t)instructionSingle.arg.BW.a_0,(uint16_t)instructionSingle.arg.BW.a_1);return;
case I_LOFF:printf("LOFF !%04X%04X",(uint16_t)(instructionSingle.arg.D.a_0>>16),(uint16_t)instructionSingle.arg.D.a_0);return;
case I_INSR:printf("INSR %%%01X",(uint16_t)instructionSingle.arg.B1.a_0);return;
}
}
